//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphanePlatformu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cezalar
    {
        public int Id { get; set; }
        public Nullable<int> Uye { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<decimal> Para { get; set; }
        public Nullable<int> KitapHareket { get; set; }
    
        public virtual KitapHareket KitapHareket1 { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
